# Header
menu:
  主页: /
  所有文章: /archives
  linux基础: /categories/linux基础
  Android底层开发: /categories/Android底层开发
  项目管理: /categories/项目管理
  Python: /categories/Python
  开源框架: /categories/开源框架
  随笔: /categories/随笔


# SubNav
subnav:
    # github: "https://github.com/ashimidashajia"
    #weibo: "http://weibo.com/u/5324408874"
  #rss: "#"
  #zhihu: "#"
  #douban: "#"
  # mail: "ashimidashajia@126.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: http://7xj6ce.com1.z0.glb.clouddn.com/android.jpg 
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: iloveandroid
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#奥巴马的博客: http://localhost:4000/
# 卡卡的美丽传说: http://localhost:4000/
# 本泽马的博客: http://localhost:4000/
# 吉格斯的博客: http://localhost:4000/
#  习大大大不同: http://localhost:4000/
# 托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 码农的成长之路，不要让昨日的悲伤，浪费今天的眼泪。
